### ISSUE TITLE
prtvol2csv, support same YML-file as Webviz

### ISSUE THREAD

**Issue by berland** [equinor/subscript#330]
Webviz already defines a yaml-syntax that prtvol2csv could have used as input to its FIPNUM <-> (Region, Zone) mapping.

An example is:

```yaml
FIPNUM:
  groups:
    REGION:
      WestLowland: [1, 8, 15]
      CentralSouth: [2, 9, 16]
      CentralNorth: [3, 10, 17]
      NorthHorst: [4, 11, 18]
      CentralRamp: [5, 12, 19]
      CentralHorst: [6, 13, 20]
      EastLowland: [7, 14, 21]
    ZONE:
      Valysar: [1, 2, 3, 4, 5, 6, 7]
      Therys: [8, 9, 10, 11, 12, 13, 14]
      Volon: [15, 16, 17, 18, 19, 20, 21]
```

Suggest to add support for this yaml format to `prtvol2csv` to allow using the same input file for both Webviz and prtvol2csv.
