### ISSUE TITLE
Investigate using setuptools `script-files` in pyproject.toml for legacy scripts

### ISSUE THREAD

**Issue by mferrera** [equinor/subscript#626]
It should be possible to use

```toml
[tool.setuptools]
script-files = ["src/subscript/legacy/{..script..}", ...]
```

in pyproject.toml for the remaining legacy scripts, after which `setup.py` can be completely removed.
