### ISSUE TITLE
Simplified obs.setup with metadata

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/subscript#683]
**Prototype description:**
* If `error` is absolute, give error if `min_error` and/or `max_error` is provided.
* Make a CLI command in `subscript-playground` which translates YAML to necessary ERT files:
    * ERT include file with GENDATA keywords + necessary FORWARD MODELS (e.g. RFT) + reference to OBS_FILE
    * Create the ERT obs-file
    * Create GENOBS-files
* To be tested on selected `fmu-dataio` / SUMO / webviz pilot fields only: Snorre, Troll, Johan Sverdrup

**YAML schema sketch:**
```yaml
- name: Gas-oil-ratio observations
  type: timeseries
  error: 10%  # optional (% indicates relative, otherwise absolute)
  min_error: 20  # optional, always absolute
  max_error: 30  # optional, always absolute
  # Columns: vector, date, value, error, min_error, max_error (last three columns optional, overrides global error)
  observation: "./input/observations/summary_gor.csv"

- name: Bottom hole pressure observations
  type: timeseries
  error: 10%  # % indicates relative, otherwise absolute
  observation: "./input/observations/summary_bhp.csv"

- name: RFT pressure observations
  type: rft  # we have a plugin that "knows about rft"
  plugin_arguments:
    zonemap: "./rms/output/zone/layer_zone_table.txt"
    trajectories: "./rms/output/trajectories.csv"
  error: 5 
  # Columns: well, date, measured_depth, zone, value, error, min_error, max_error (last three columns optional)
  observation: "./input/observations/rft_pressure.csv"
  metadata:
    columns:
      measured_depth:
         unit: m
         reference: msl
      value:
         unit: bar

- name: RFT saturation observations
  type: rft  # we have a plugin that "knows about rft"
  plugin_arguments:
    zonemap: "./rms/output/zone/layer_zone_table.txt"
    trajectories: "./rms/output/trajectories.csv"
  error: 5 
  # Columns: well, date, measured_depth, zone, value, error, min_error, max_error (last three columns optional)
  observation: "./input/observations/rft_saturation.csv"
  metadata:
    columns:
      measured_depth:
         unit: m
         reference: msl
      value:
         unit: fraction

# - # name: 4D gravity
  # type: gravity
  # observation: "./"
  # observations:
  #   # gravity plugin makes the N^2 combinations
  #   - value: 100
  #     error: 5
  #     coordinate:
  #       station_name: xxx
  #       date: 2003-01-01
```
