### ISSUE TITLE
[merge_schedule] Not reproducing resscript merge_schedule

### ISSUE THREAD

**Issue by berland** [equinor/subscript#77]
merge_schedule (in subscript) does not support having statements before the first DATES keyword. This was supported by the resscript-version.

Sunsch supports this, but it is a little bit tricky to fix in merge_schedule, as the yaml setup must be dependent on whether the first to-merge file actually has statements at the front.

If it has statements, then the yaml sent to sunsch should look like this:
```yaml
        sunsch_config = { 
            "startdate": datetime.date(1900, 1, 1), 
            "init": args.inputfiles[0],
            "merge": args.inputfiles[1:],
        }   
```
but if  `args.inputfiles[0]` starts right away with DATES, then `init`  should be dropped and `merge` should contain all inputfiles.
