### ISSUE TITLE
[sunsch] Configuration file format

### ISSUE THREAD

**Issue by berland** [equinor/subscript#98]
The current configuration of the inserts read like this in the example:
```
 insert:
   - foo1.sch: # filename is read from this line unless filename is supplied
       date: 2020-01-01
   - randomidentifier:
       filename: foo1.sch
       date: 2021-01-01
   - foo1.sch:
       days: 100
   - randomid:
       days: 40
       string: "WCONHIST\n  A-4 OPEN ORAT 5000 /\n/"
   - substitutetest:
       days: 2
       filename: footemplate.sch
       substitute:  { ORAT: 3000, GRAT: 400000}
   - footemplate.sch:
       days: 10
       substitute:
         ORAT: 30000
         GRAT: 100
```
A problem with this is the keys on the first level of the list of dictionaries, `foo1.sch`, `randomidentifier`, `randomid` etc. These are only in used if they refer to filenames, and are nothing but noise in the case of `randomid`. This is likely to confuse users. The indendation required is also likely to lead to user errors.

Official doc is on: https://wiki.equinor.com/wiki/index.php/ResScript:Python:Scripts:sunsch
